core: "VanillaVAE2"
criterion: "mmd"
strategy: "paired" # Using paired decoder structure
loss_type: "A" # Only involve reconstruction loss
learning_rate: 0.0005
epochs: 100
early_stop: 10
save_period: 10
paired_chars: ["jin", "chu"] # Bronze -> Chu State
level: "instance"
model_params:
  in_channels: 1
  input_size: 96
  latent_dim: 128
  hidden_dims: 5

