core: "VanillaVAE2"
criterion: "mmd"
strategy: "paired" # Using paired decoder structure
loss_type: "B" # Only involve reconstruction loss
learning_rate: 0.001
epochs: 100
early_stop: 10
save_period: 10
paired_chars: ["jia", "jin"] # Oracle -> Bronze
level: "instance"
model_params:
  in_channels: 1
  input_size: 96
  latent_dim: 64
  hidden_dims: 4

