core: "VanillaVAE"
criterion: "mmd"
strategy: "single" # Using single decoder structure
loss_type: "A" # Calculate mmd distance loss
learning_rate: 0.001
epochs: 100
early_stop: 15
save_period: 10
paired_chars: ["jia", "jin"] # Oracle -> Bronze
level: "instance"
model_params:
  in_channels: 1
  input_size: 96
  latent_dim: 128
  hidden_dims: 5

